/**
 * Station art from Sol (R1.1; 33 independent 1x PNG), inlined by esbuild as data URLs.
 * Generated by scripts/station-assets.mjs from assets/station/manifest.json; build.mjs verifies every hash.
 */
import sstation_npc_xu_s_idle_f0_v1 from '../../assets/station/v1/station-npc-xu-s-idle-f0-v1.png';
import sstation_npc_xu_s_idle_f1_v1 from '../../assets/station/v1/station-npc-xu-s-idle-f1-v1.png';
import sstation_npc_xu_s_talk_f0_v1 from '../../assets/station/v1/station-npc-xu-s-talk-f0-v1.png';
import sstation_npc_xu_s_talk_f1_v1 from '../../assets/station/v1/station-npc-xu-s-talk-f1-v1.png';
import sstation_npc_shuan_s_idle_f0_v1 from '../../assets/station/v1/station-npc-shuan-s-idle-f0-v1.png';
import sstation_npc_shuan_s_idle_f1_v1 from '../../assets/station/v1/station-npc-shuan-s-idle-f1-v1.png';
import sstation_npc_shuan_s_talk_f0_v1 from '../../assets/station/v1/station-npc-shuan-s-talk-f0-v1.png';
import sstation_npc_shuan_s_talk_f1_v1 from '../../assets/station/v1/station-npc-shuan-s-talk-f1-v1.png';
import sstation_npc_shuan_n_work_f0_v1 from '../../assets/station/v1/station-npc-shuan-n-work-f0-v1.png';
import sstation_npc_shuan_n_work_f1_v1 from '../../assets/station/v1/station-npc-shuan-n-work-f1-v1.png';
import sstation_npc_cai_s_idle_f0_v1 from '../../assets/station/v1/station-npc-cai-s-idle-f0-v1.png';
import sstation_npc_cai_s_idle_f1_v1 from '../../assets/station/v1/station-npc-cai-s-idle-f1-v1.png';
import sstation_npc_cai_s_talk_f0_v1 from '../../assets/station/v1/station-npc-cai-s-talk-f0-v1.png';
import sstation_npc_cai_s_talk_f1_v1 from '../../assets/station/v1/station-npc-cai-s-talk-f1-v1.png';
import sstation_npc_cai_n_work_f0_v1 from '../../assets/station/v1/station-npc-cai-n-work-f0-v1.png';
import sstation_npc_cai_n_work_f1_v1 from '../../assets/station/v1/station-npc-cai-n-work-f1-v1.png';
import sstation_npc_cook_s_idle_f0_v1 from '../../assets/station/v1/station-npc-cook-s-idle-f0-v1.png';
import sstation_npc_cook_s_idle_f1_v1 from '../../assets/station/v1/station-npc-cook-s-idle-f1-v1.png';
import sstation_npc_cook_s_talk_f0_v1 from '../../assets/station/v1/station-npc-cook-s-talk-f0-v1.png';
import sstation_npc_cook_s_talk_f1_v1 from '../../assets/station/v1/station-npc-cook-s-talk-f1-v1.png';
import sstation_npc_cook_n_work_f0_v1 from '../../assets/station/v1/station-npc-cook-n-work-f0-v1.png';
import sstation_npc_cook_n_work_f1_v1 from '../../assets/station/v1/station-npc-cook-n-work-f1-v1.png';
import sstation_prop_counter_v1 from '../../assets/station/v1/station-prop-counter-v1.png';
import sstation_prop_desk_v1 from '../../assets/station/v1/station-prop-desk-v1.png';
import sstation_prop_radio_desk_v1 from '../../assets/station/v1/station-prop-radio-desk-v1.png';
import sstation_prop_generator_stopped_v1 from '../../assets/station/v1/station-prop-generator-stopped-v1.png';
import sstation_prop_generator_running_v1 from '../../assets/station/v1/station-prop-generator-running-v1.png';
import sstation_prop_stove_v1 from '../../assets/station/v1/station-prop-stove-v1.png';
import sstation_prop_pool_v1 from '../../assets/station/v1/station-prop-pool-v1.png';
import sstation_prop_radio_desk_emit_v1 from '../../assets/station/v1/station-prop-radio-desk-emit-v1.png';
import sstation_prop_generator_stopped_emit_v1 from '../../assets/station/v1/station-prop-generator-stopped-emit-v1.png';
import sstation_prop_generator_running_emit_v1 from '../../assets/station/v1/station-prop-generator-running-emit-v1.png';
import sstation_prop_stove_emit_v1 from '../../assets/station/v1/station-prop-stove-emit-v1.png';

export const STATION_ASSET_URLS: Record<string, string> = {
  'station-npc-xu-s-idle-f0-v1': sstation_npc_xu_s_idle_f0_v1,
  'station-npc-xu-s-idle-f1-v1': sstation_npc_xu_s_idle_f1_v1,
  'station-npc-xu-s-talk-f0-v1': sstation_npc_xu_s_talk_f0_v1,
  'station-npc-xu-s-talk-f1-v1': sstation_npc_xu_s_talk_f1_v1,
  'station-npc-shuan-s-idle-f0-v1': sstation_npc_shuan_s_idle_f0_v1,
  'station-npc-shuan-s-idle-f1-v1': sstation_npc_shuan_s_idle_f1_v1,
  'station-npc-shuan-s-talk-f0-v1': sstation_npc_shuan_s_talk_f0_v1,
  'station-npc-shuan-s-talk-f1-v1': sstation_npc_shuan_s_talk_f1_v1,
  'station-npc-shuan-n-work-f0-v1': sstation_npc_shuan_n_work_f0_v1,
  'station-npc-shuan-n-work-f1-v1': sstation_npc_shuan_n_work_f1_v1,
  'station-npc-cai-s-idle-f0-v1': sstation_npc_cai_s_idle_f0_v1,
  'station-npc-cai-s-idle-f1-v1': sstation_npc_cai_s_idle_f1_v1,
  'station-npc-cai-s-talk-f0-v1': sstation_npc_cai_s_talk_f0_v1,
  'station-npc-cai-s-talk-f1-v1': sstation_npc_cai_s_talk_f1_v1,
  'station-npc-cai-n-work-f0-v1': sstation_npc_cai_n_work_f0_v1,
  'station-npc-cai-n-work-f1-v1': sstation_npc_cai_n_work_f1_v1,
  'station-npc-cook-s-idle-f0-v1': sstation_npc_cook_s_idle_f0_v1,
  'station-npc-cook-s-idle-f1-v1': sstation_npc_cook_s_idle_f1_v1,
  'station-npc-cook-s-talk-f0-v1': sstation_npc_cook_s_talk_f0_v1,
  'station-npc-cook-s-talk-f1-v1': sstation_npc_cook_s_talk_f1_v1,
  'station-npc-cook-n-work-f0-v1': sstation_npc_cook_n_work_f0_v1,
  'station-npc-cook-n-work-f1-v1': sstation_npc_cook_n_work_f1_v1,
  'station-prop-counter-v1': sstation_prop_counter_v1,
  'station-prop-desk-v1': sstation_prop_desk_v1,
  'station-prop-radio-desk-v1': sstation_prop_radio_desk_v1,
  'station-prop-generator-stopped-v1': sstation_prop_generator_stopped_v1,
  'station-prop-generator-running-v1': sstation_prop_generator_running_v1,
  'station-prop-stove-v1': sstation_prop_stove_v1,
  'station-prop-pool-v1': sstation_prop_pool_v1,
  'station-prop-radio-desk-emit-v1': sstation_prop_radio_desk_emit_v1,
  'station-prop-generator-stopped-emit-v1': sstation_prop_generator_stopped_emit_v1,
  'station-prop-generator-running-emit-v1': sstation_prop_generator_running_emit_v1,
  'station-prop-stove-emit-v1': sstation_prop_stove_emit_v1,
};
/** Size and emission mask of every delivered asset, from the manifest. */
export const STATION_ASSET_META: Record<string, { w: number; h: number; emit: string | null }> = {
  'station-npc-xu-s-idle-f0-v1': { w: 32, h: 48, emit: null },
  'station-npc-xu-s-idle-f1-v1': { w: 32, h: 48, emit: null },
  'station-npc-xu-s-talk-f0-v1': { w: 32, h: 48, emit: null },
  'station-npc-xu-s-talk-f1-v1': { w: 32, h: 48, emit: null },
  'station-npc-shuan-s-idle-f0-v1': { w: 32, h: 48, emit: null },
  'station-npc-shuan-s-idle-f1-v1': { w: 32, h: 48, emit: null },
  'station-npc-shuan-s-talk-f0-v1': { w: 32, h: 48, emit: null },
  'station-npc-shuan-s-talk-f1-v1': { w: 32, h: 48, emit: null },
  'station-npc-shuan-n-work-f0-v1': { w: 32, h: 48, emit: null },
  'station-npc-shuan-n-work-f1-v1': { w: 32, h: 48, emit: null },
  'station-npc-cai-s-idle-f0-v1': { w: 32, h: 48, emit: null },
  'station-npc-cai-s-idle-f1-v1': { w: 32, h: 48, emit: null },
  'station-npc-cai-s-talk-f0-v1': { w: 32, h: 48, emit: null },
  'station-npc-cai-s-talk-f1-v1': { w: 32, h: 48, emit: null },
  'station-npc-cai-n-work-f0-v1': { w: 32, h: 48, emit: null },
  'station-npc-cai-n-work-f1-v1': { w: 32, h: 48, emit: null },
  'station-npc-cook-s-idle-f0-v1': { w: 32, h: 48, emit: null },
  'station-npc-cook-s-idle-f1-v1': { w: 32, h: 48, emit: null },
  'station-npc-cook-s-talk-f0-v1': { w: 32, h: 48, emit: null },
  'station-npc-cook-s-talk-f1-v1': { w: 32, h: 48, emit: null },
  'station-npc-cook-n-work-f0-v1': { w: 32, h: 48, emit: null },
  'station-npc-cook-n-work-f1-v1': { w: 32, h: 48, emit: null },
  'station-prop-counter-v1': { w: 128, h: 54, emit: null },
  'station-prop-desk-v1': { w: 64, h: 52, emit: null },
  'station-prop-radio-desk-v1': { w: 96, h: 70, emit: 'station-prop-radio-desk-emit-v1' },
  'station-prop-generator-stopped-v1': { w: 64, h: 98, emit: 'station-prop-generator-stopped-emit-v1' },
  'station-prop-generator-running-v1': { w: 64, h: 98, emit: 'station-prop-generator-running-emit-v1' },
  'station-prop-stove-v1': { w: 96, h: 62, emit: 'station-prop-stove-emit-v1' },
  'station-prop-pool-v1': { w: 96, h: 72, emit: null },
  'station-prop-radio-desk-emit-v1': { w: 96, h: 70, emit: null },
  'station-prop-generator-stopped-emit-v1': { w: 64, h: 98, emit: null },
  'station-prop-generator-running-emit-v1': { w: 64, h: 98, emit: null },
  'station-prop-stove-emit-v1': { w: 96, h: 62, emit: null },
};
