import assert from 'node:assert/strict';
import { mkdir, writeFile, readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { createHash } from 'node:crypto';
import { pathToFileURL } from 'node:url';
import { chromium } from 'playwright';
import { MALL_WORLD } from '../src/mall-world.ts';
import { traversable } from '../src/spatial.ts';
import { browserOptions } from './browser-options.mjs';
const out=resolve('test-results');await mkdir(out,{recursive:true});
const report={htmlSha256:createHash('sha256').update(await readFile('dist/index.html')).digest('hex'),startedAt:new Date().toISOString(),methodology:'Offline native mall E input. Explicit candidates move the original 25 enemy identities to obstruct target landing slots, set long attack cooldowns, and then clear exactly one slot. No fabricated enemy identities or reset population.',steps:[],errors:[],requests:[]};
const browser=await chromium.launch(browserOptions);report.browser=browser.version();const ctx=await browser.newContext({viewport:{width:1280,height:720},offline:true}),page=await ctx.newPage();page.setDefaultTimeout(12000);page.on('pageerror',e=>report.errors.push(e.stack??e.message));ctx.on('request',r=>{if(/^https?:/.test(r.url()))report.requests.push(r.url());});
const entry=MALL_WORLD.maps['mall-f1'].entries.find(e=>e.id==='S-N-up'),at=entry.landing,slots=[];
for(let y=-2;y<=2;y++)for(let x=-2;x<=2;x++){const p={x:at.x+x*32,y:at.y+y*32};if(Math.hypot(p.x-at.x,p.y-at.y)<=64&&traversable({definition:MALL_WORLD.maps['mall-f2'],doors:{},highTide:true},p,'body',10))slots.push(p);}
const snapshot=()=>page.evaluate(()=>{const s=window.__bincov.app.raid.snapshotExpansion();return{map:s.raid.currentMap,player:s.raid.player,enemies:Object.values(s.raid.maps).flatMap(m=>m.enemies).map(e=>e.uid).sort(),roster:s.raid.roster,pursuits:s.raid.pursuits};});
async function fixture(count){await page.evaluate(({entry,slots,count})=>{const s=window.__bincov.saveSession,t=s.prepareExpansionMutation(d=>{const r=d.expansion.raid;r.currentMap='mall-f1';r.player={...entry.at,rotation:0};d.expansion.body.hp=100;d.expansion.body.stamina=100;d.expansion.body.bleeding=false;const source=r.maps['mall-f1'],target=r.maps['mall-f2'];const moved=source.enemies.splice(0,count);moved.forEach((e,i)=>Object.assign(e,slots[i],{home:{...slots[i]},target:{...slots[i]},state:'patrol',timer:1000,cooldown:1000,path:[],alert:0}));target.enemies.push(...moved);for(const m of Object.values(r.maps))for(const e of m.enemies)e.cooldown=1000;});if(!t||s.commitExpansionMutation(t)!=='committed')throw new Error('Landing fixture rejected');},{entry,slots,count});}
try{
 await page.goto(pathToFileURL(resolve('dist/index.html')).href+'?test=1&entry=tabs');await page.locator('[data-action="enter"]').click();await page.locator('#run-world').selectOption('mall');await page.locator('#seed').fill('41');await page.locator('[data-action="deploy"]').click();await page.waitForFunction(()=>window.__bincov.app.raid?.player?.active);
 await fixture(slots.length);const before=await snapshot();await page.keyboard.press('e');await page.waitForTimeout(150);const blocked=await snapshot();assert.equal(blocked.map,'mall-f1');assert.deepEqual(blocked.enemies,before.enemies);assert.equal(blocked.pursuits.length,0);assert.match(await page.locator('#toast').innerText(),/入口被挡住/);report.steps.push({name:'all legal landing slots occupied: stays on F1 without population transfer',status:'passed',slots:slots.length});await page.screenshot({path:resolve(out,'mall-landing-blocked-1280x720.png')});
 await page.evaluate(at=>{const s=window.__bincov.saveSession,t=s.prepareExpansionMutation(d=>{const r=d.expansion.raid,target=r.maps['mall-f2'],enemy=target.enemies.find(e=>Math.hypot(e.x-at.x,e.y-at.y)<1);Object.assign(enemy,{x:1136,y:752,home:{x:1136,y:752},target:{x:1136,y:752}});});if(!t||s.commitExpansionMutation(t)!=='committed')throw new Error('Clear-one fixture rejected');},at);
 await page.keyboard.down('w');await page.mouse.down();await page.keyboard.down('e');await page.waitForFunction(()=>window.__bincov.app.expansion.raid.currentMap==='mall-f2');await page.waitForTimeout(5000);const landed=await snapshot();assert.equal(landed.map,'mall-f2');assert.deepEqual(landed.player,{...at,rotation:landed.player.rotation});assert.deepEqual(landed.enemies,before.enemies);assert.equal(landed.pursuits.length,0);await page.keyboard.up('w');await page.mouse.up();await page.keyboard.up('e');report.steps.push({name:'one slot cleared: specified landing accepted once; five-second held E/move/fire stays suppressed',status:'passed'});await page.screenshot({path:resolve(out,'mall-landing-clear-1280x720.png')});
 assert.deepEqual(report.errors,[]);assert.deepEqual(report.requests,[]);report.status='passed';console.log('PASS mall blocked landing, one-slot retry and five-second held input');
}catch(e){report.status='failed';report.failure=e.stack;console.error(e);process.exitCode=1;}
finally{report.finishedAt=new Date().toISOString();await writeFile(resolve(out,'mall-landing-report.json'),JSON.stringify(report,null,2));await ctx.close();await browser.close();}
