import { chromium } from 'playwright';
import { pathToFileURL } from 'node:url';
import { resolve } from 'node:path';
import { mkdir } from 'node:fs/promises';
await mkdir('test-results',{recursive:true});
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--allow-file-access-from-files']});
const page=await browser.newPage({viewport:{width:1280,height:720}});
page.on('pageerror',e=>console.log('PAGE ERROR:',e.message));
await page.goto(pathToFileURL(resolve('dist/index.html')).href+'?test=1&entry=tabs');
await page.waitForSelector('[data-action="enter"]');
await page.screenshot({path:'test-results/menu.png'});
await page.click('[data-action="enter"]');
await page.waitForSelector('[data-action="deploy"]');
await page.screenshot({path:'test-results/hideout.png'});
await page.fill('#seed','42');
await page.click('[data-action="deploy"]');
await page.waitForFunction(()=>window.__bincov.app.raid?.player?.active);
await page.waitForTimeout(1000);
await page.screenshot({path:'test-results/raid.png'});
console.log(await page.evaluate(()=>({state:window.__bincov.app.state,raid:!!window.__bincov.app.raid,active:window.__bincov.app.game.scene.getScenes(true).map(s=>s.scene.key),enemies:window.__bincov.app.raid.enemies.length,loot:window.__bincov.app.raid.loot.length})));
await browser.close();
