// Tide and pickup use real Runtime state changes and native input; only time/location/loot fixtures are explicit.
import assert from 'node:assert/strict';import{mkdir,writeFile,readFile}from'node:fs/promises';import{resolve}from'node:path';import{pathToFileURL}from'node:url';import{createHash}from'node:crypto';import{chromium}from'playwright';import{browserOptions}from'./browser-options.mjs';
const out=resolve(process.env.BINCOV_R7_OUT||'test-results/sol-r7-20261009/tide');await mkdir(out,{recursive:true});const report={startedAt:new Date().toISOString(),node:process.version,htmlSHA256:createHash('sha256').update(await readFile('dist/index.html')).digest('hex'),method:'Seeds 3/42, four viewport sizes. Legal transactional elapsed=299.7 fixture, real subsequent frames cross 300s. Native movement/E pickup, native inventory drop creates a genuine water ground UID at the tide cell; no arbitrary relocation. Reduced motion and reload/map boundaries. No synthetic flooded list.',runs:[],errors:[],requests:[]};const b=await chromium.launch(browserOptions);report.browser=b.version();const wait=ms=>new Promise(r=>setTimeout(r,ms));
const configs=[...[{width:1280,height:720},{width:1920,height:1080},{width:844,height:390},{width:640,height:300}].flatMap(size=>[3,42].map(seed=>({size,seed,reduced:false}))),...[3,42].map(seed=>({size:{width:1280,height:720},seed,reduced:true}))];
try{for(const config of configs){const {size,seed,reduced}=config,row={...config,status:'running'};report.runs.push(row);const c=await b.newContext({viewport:size,offline:true,hasTouch:size.width<1000,deviceScaleFactor:size.width<1000?3:1,reducedMotion:reduced?'reduce':'no-preference'}),p=await c.newPage();p.setDefaultTimeout(15000);p.on('pageerror',e=>report.errors.push(e.message));c.on('request',r=>{if(/^https?:/.test(r.url()))report.requests.push(r.url());});const id=seed+'-'+size.width+'x'+size.height+'-'+reduced;
const read=()=>p.evaluate(()=>{const h=window.__bincovSample.host,b=h.lastBatch,g=h.view.actors.get('player');return{high:b.frame.highTide,sim:b.stamp.simulationTime,flooded:[...b.frame.flooded],shown:h.view.tide.shown,alpha:h.view.tide.alpha,foam:h.view.tide.foam.alpha,position:{x:b.frame.player.x,y:b.frame.player.y},wade:g.wade.visible,shadow:g.shadow.visible,map:b.stamp.world.mapId,loot:b.frame.loot.map(l=>({uid:l.uid,x:l.x,y:l.y,item:l.item,alpha:h.view.loot.get(l.uid)?.alpha,tint:h.view.loot.get(l.uid)?.tint})),interaction:b.frame.interaction,phase:b.frame.phase,panel:h.panel};});
try{await p.goto(pathToFileURL(resolve('dist/index.html')).href+'?test=1&entry=tabs&sample=village');await p.locator('[data-action="enter"]').click();await p.locator('#seed').fill(String(seed));await p.locator('[data-action="deploy"]').click();await p.waitForFunction(()=>!!window.__bincovSample?.host?.lastBatch);await p.evaluate(()=>window.__bincovSample.driver.freezeAI(true));await p.evaluate(()=>window.__bincovSample.driver.placePlayer({x:2000,y:400},0,'coast'));await wait(300);
row.initial=await read();assert.equal(row.initial.high,seed===3);assert.equal(row.initial.flooded.length,seed===3?106:0);assert.equal(row.initial.alpha,seed===3?1:0);
const drop=async()=>{await p.evaluate(()=>window.__bincovSample.driver.placePlayer({x:2032,y:400},0,'coast'));await wait(100);const before=await p.evaluate(()=>window.__bincovSample.host.lastBatch.frame.loot.map(l=>l.uid));await p.evaluate(()=>{const s=window.__bincov.saveSession,t=s.prepareExpansionMutation(d=>{d.expansion.raid.loadout.bag.items=[{uid:'r7-tide-water',id:'water',qty:1,x:0,y:0}];});if(!t||s.commitExpansionMutation(t)!=='committed')throw Error('bag fixture');});await p.keyboard.press('Tab');await p.waitForFunction(()=>window.__bincovSample.host.panel==='inventory');await p.locator('[data-source="bag"][data-uid="r7-tide-water"]').click();await p.locator('[data-do="inv-drop"]').click();await p.keyboard.press('Escape');await p.waitForFunction(()=>window.__bincovSample.host.panel===null);await p.waitForFunction(ids=>window.__bincovSample.host.lastBatch.frame.loot.some(l=>!ids.includes(l.uid)),before);const l=await p.evaluate(ids=>window.__bincovSample.host.lastBatch.frame.loot.find(l=>!ids.includes(l.uid)),before);assert.equal(l.item,'water');assert.equal(l.x,2032);assert.equal(l.y,400);await p.evaluate(()=>window.__bincovSample.driver.placePlayer({x:2000,y:400},0,'coast'));await wait(200);return l;};
row.lootFixture=await drop();await p.screenshot({path:resolve(out,id+'-initial.png')});let uid=row.lootFixture.uid;row.itemBefore=await read();const ls=row.itemBefore.loot.find(l=>l.uid===uid);assert(ls);assert.equal(ls.alpha,seed===3?.6:1);if(seed===3)assert.equal(ls.tint,0x8a9e96);
await p.keyboard.press('e');await wait(250);row.pickupBefore=await p.evaluate(u=>({exists:window.__bincovSample.host.lastBatch.frame.loot.some(l=>l.uid===u),bag:window.__bincov.app.loadout.bag.items.filter(i=>i.id==='water').reduce((n,i)=>n+i.qty,0)}),uid);assert.equal(row.pickupBefore.exists,seed===3);assert.equal(row.pickupBefore.bag,seed===3?0:1);
if(seed===42){row.secondDrop=await drop();uid=row.secondDrop.uid;}
await p.evaluate(()=>{const s=window.__bincov.saveSession,t=s.prepareExpansionMutation(d=>{const r=d.expansion.raid;r.elapsed=299.7;r.warned=true;r.tideChanged=false;});if(!t||s.commitExpansionMutation(t)!=='committed')throw Error('elapsed fixture');window.__r7Tide=[];const h=window.__bincovSample.host,normal=h.view.present;h.view.present=function(b,dt){normal.call(this,b,dt);window.__r7Tide.push({sim:b.stamp.simulationTime,high:b.frame.highTide,alpha:this.tide.alpha,shown:this.tide.shown.length,viewTime:this.time});};});
await p.waitForFunction(high=>window.__bincovSample.host.lastBatch.frame.highTide!==high,seed===3);await wait(100);row.flipEarly=await read();await wait(1700);row.flipEnd=await read();assert.equal(row.flipEnd.high,seed!==3);assert.equal(row.flipEnd.alpha,seed===3?0:1);assert.equal(row.flipEnd.shown.length,seed===3?0:106);row.timeline=await p.evaluate(()=>window.__r7Tide);const changed=row.timeline.filter(x=>x.high!==(seed===3));assert(changed.length>5);if(reduced)assert(changed.every(x=>x.alpha===(seed===3?0:1)));else assert(changed.some(x=>x.alpha>0&&x.alpha<1));await p.screenshot({path:resolve(out,id+'-flipped.png')});
await p.keyboard.press('e');await wait(250);row.pickupAfter=await p.evaluate(u=>({exists:window.__bincovSample.host.lastBatch.frame.loot.some(l=>l.uid===u),bag:window.__bincov.app.loadout.bag.items.filter(i=>i.id==='water').reduce((n,i)=>n+i.qty,0)}),uid);assert.equal(row.pickupAfter.exists,seed!==3);assert.equal(row.pickupAfter.bag,seed===3?1:0);
await p.keyboard.down('d');await wait(450);await p.keyboard.up('d');row.movement=await read();if(seed===3)assert(row.movement.position.x>2016);else assert(row.movement.position.x<2006.5);
if(seed===42){await p.evaluate(()=>window.__bincovSample.driver.placePlayer({x:2032,y:400},0,'coast'));await wait(300);row.wading=await read();assert(row.wading.wade&&!row.wading.shadow);await p.screenshot({path:resolve(out,id+'-wading.png')});await p.keyboard.down('a');await wait(800);await p.keyboard.up('a');row.escaped=await read();assert(row.escaped.position.x<2000);assert(!row.escaped.wade&&row.escaped.shadow);}
if(size.width===1280&&seed===42&&!reduced){assert(await p.evaluate(()=>window.__bincovSample.host.services.checkpoint()));await p.reload();await p.locator('[data-action="enter"]').click();await p.waitForFunction(()=>!!window.__bincovSample?.host?.lastBatch);row.reload=await read();assert.equal(row.reload.high,true);assert.equal(row.reload.alpha,1);assert.equal(row.reload.flooded.length,106);await p.locator('[data-do="resume"]').click();await p.waitForFunction(()=>window.__bincovSample.host.lastBatch.frame.phase==='running');await p.evaluate(()=>window.__bincovSample.driver.freezeAI(true));row.layers=[];for(const [map,x]of [['resident-f2',304],['resident-b1',240],['coast',2000]]){await p.evaluate(([map,x])=>window.__bincovSample.driver.placePlayer({x,y:map==='coast'?400:80},0,map),[map,x]);await wait(200);const r=await read();row.layers.push(r);assert.equal(r.flooded.length,map==='coast'?106:0);assert.equal(r.alpha,map==='coast'?1:0);}}
row.status='passed';}catch(e){row.status='failed';row.error=e.stack;row.failureState=await read().catch(()=>null);await p.screenshot({path:resolve(out,id+'-failed.png')}).catch(()=>{});process.exitCode=1;}finally{await c.close();await writeFile(resolve(out,'tide.json'),JSON.stringify(report,null,2)+'\n');console.log(row.status,id,row.error?.split('\n')[0]??'');}}
}finally{await b.close();report.finishedAt=new Date().toISOString();await writeFile(resolve(out,'tide.json'),JSON.stringify(report,null,2)+'\n');}assert.deepEqual(report.errors,[]);assert.deepEqual(report.requests,[]);
