// Generate src/station-view/assets.ts from assets/station/manifest.json (Sol's station delivery).
// Usage: node scripts/station-assets.mjs
// Every PNG must match its manifest SHA-256; build.mjs checks the same again on every build.
import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';

const manifest = JSON.parse(await readFile('assets/station/manifest.json', 'utf8'));
const sha = b => createHash('sha256').update(b).digest('hex');
const lines = [], table = [], meta = [];
for (const a of manifest.assets) {
  const bytes = await readFile(a.file);
  if (sha(bytes) !== a.sha256) throw new Error(`Hash mismatch: ${a.id}`);
  if (bytes.readUInt32BE(16) !== a.w || bytes.readUInt32BE(20) !== a.h) throw new Error(`Size mismatch: ${a.id}`);
  const name = 's' + a.id.replace(/[^a-z0-9]/gi, '_');
  lines.push(`import ${name} from '../../${a.file}';`);
  table.push(`  '${a.id}': ${name},`);
  meta.push(`  '${a.id}': { w: ${a.w}, h: ${a.h}, emit: ${a.emit ? `'${a.emit}'` : 'null'} },`);
}
const out = `/**
 * Station art from Sol (${manifest.release ?? 'delivery'}; ${manifest.assets.length} independent 1x PNG), inlined by esbuild as data URLs.
 * Generated by scripts/station-assets.mjs from assets/station/manifest.json; build.mjs verifies every hash.
 */
${lines.join('\n')}

export const STATION_ASSET_URLS: Record<string, string> = {
${table.join('\n')}
};
/** Size and emission mask of every delivered asset, from the manifest. */
export const STATION_ASSET_META: Record<string, { w: number; h: number; emit: string | null }> = {
${meta.join('\n')}
};
`;
await writeFile('src/station-view/assets.ts', out);
console.log(`src/station-view/assets.ts: ${manifest.assets.length} assets`);
